name: Deploy to Heroku
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.target_commitish }}
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download JAR from GitHub Packages
        run: |
          mvn dependency:get \
            -Dartifact=com.example:demo-webapp:${{ github.event.release.tag_name }} \
            -DrepoUrl=https://maven.pkg.github.com/${{ github.repository }} \
            -Dtransitive=false
          cp ~/.m2/repository/com/example/demo-webapp/${{ github.event.release.tag_name }}/demo-webapp-${{ github.event.release.tag_name }}.jar target/demo-webapp.jar
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: false
          branch: ${{ github.event.release.target_commitish }}
