name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw clean package

      # Using official Heroku CLI for deployment instead of deprecated action
      - name: Login to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          justlogin: true

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git config --global user.email "${{ secrets.HEROKU_EMAIL }}"
          git config --global user.name "GitHub Actions"
          heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}
          heroku config:set JAVA_OPTS="-XX:+UseContainerSupport" -a ${{ secrets.HEROKU_APP_NAME }}
          git push heroku HEAD:main --force
