name: Deploy to Heroku

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GH_TOKEN

      - name: Build and publish main webapp
        run: |
          echo "Current version from pom.xml:"
          mvn help:evaluate -Dexpression=project.version -q -DforceStdout
          
          echo "Publishing to GitHub Packages..."
          mvn -B clean deploy -DskipTests \
            -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }} \
            --file pom.xml
          
          echo "Verifying published artifact..."
          mvn dependency:get \
            -DremoteRepositories=github::default::https://maven.pkg.github.com/${{ github.repository }} \
            -DgroupId=com.example \
            -DartifactId=demo-webapp \
            -Dversion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) \
            -Dpackaging=war \
            -Dtransitive=false
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.GH_TOKEN }}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: "https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/hello"
          rollbackonhealthcheckfailed: true
          justlogin: false
          appdir: "."
          procfile: "web: java $JAVA_OPTS -jar target/dependency/jetty-runner.jar --port $PORT target/demo-webapp.war"

      - name: Verify Deployment
        run: |
          # Give the app a moment to start
          sleep 10
          # Try the health endpoint first
          if curl -f "https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/hello"; then
            echo "Deployment verified successfully"
            exit 0
          else
            echo "Health check failed"
            exit 1
          fi
