name: Deploy to Heroku

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Build and publish main webapp
        run: |
          echo "Current version from pom.xml:"
          mvn help:evaluate -Dexpression=project.version -q -DforceStdout
          
          echo "Publishing to GitHub Packages..."
          mvn -B clean deploy -DskipTests \
            -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{ github.repository }} \
            --file pom.xml
          
          echo "Verifying published artifact..."
          mvn dependency:get \
            -DremoteRepositories=github::default::https://maven.pkg.github.com/${{ github.repository }} \
            -DgroupId=com.example \
            -DartifactId=demo-webapp \
            -Dversion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout) \
            -Dpackaging=war \
            -Dtransitive=false
          
          echo "Building consumer app..."
          cd consumer-app
          mvn -B clean package -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          MAVEN_USERNAME: ${{ github.actor }}
          MAVEN_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: "https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/hello"
          rollbackonhealthcheckfailed: true
          justlogin: false

      - name: Verify Deployment
        run: |
          curl -f https://${{ secrets.HEROKU_APP_NAME }}.herokuapp.com/health || exit 1
